apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p5tv8su1y-java-quarkus
  janus-idp.io/tekton: p5tv8su1y-java-quarkus
  backstage.io/kubernetes-id: p5tv8su1y-java-quarkus
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: p5tv8su1y-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
